[build]
rustflags = ["-C", "target-cpu=native", "-Z", "tune-cpu=native"]

[profile.release]
rustflags = [
    "-Z",
    "mir-opt-level=3",
    "-C",
    "llvm-args=-inline-threshold=1000",
    "-C",
    "llvm-args=-unroll-threshold=1000",
    "-C",
    "llvm-args=-enable-unsafe-fp-math",
]

[profile.dev]
rustflags = ["-Z", "codegen-backend=cranelift"]

[env]
RUST_BACKTRACE = "full"

[alias]
test = "nextest run --config .cargo/nextest.toml"
cov = "llvm-cov nextest --config .cargo/nextest.toml"
lcov = "llvm-cov nextest --lcov --output-path lcov.info --config .cargo/nextest.toml"
flame = "flamegraph --profile=release-with-debug"
clear = ["clean", "cache -a"]
fmt = "fmt -- --config version=2024,style_version=2024"
fixes = ["clippy --fix --allow-dirty", "fmt"]
doc = "doc --no-deps"
mir = "miri test"
audit = "audit"

[unstable]
advanced-env = true
codegen-backend = true
build-std = ["std"]
